src/debian_reimbursements/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("reports/", include("reports.urls")),
    path("requests/", include("reimbursements.urls")),
    path("", include("webui.urls")),
]

src/reimbursements/urls.py
from django.urls import path

from reimbursements.views.bank_details import (
    BankDetailsView,
    BankFormSelectorView,
)
from reimbursements.views.lifecycle import (
    RequestCommentView,
    RequestDeleteView,
    RequestReimburseReturnView,
    RequestReimburseView,
    RequestReviewView,
    RequestSubmitDraftView,
    RequestSubmitIncreaseView,
    RequestSubmitView,
)
from reimbursements.views.receipt import (
    ReceiptCreateView,
    ReceiptDeleteView,
    ReceiptEditView,
    ReceiptFileView,
    ReceiptThumbnailView,
    RequestReceiptsView,
)
from reimbursements.views.request import (
    RequestCreateView,
    RequestCurrencyChangeView,
    RequestEditView,
    RequestPDFBundleView,
    RequestBeancountView,
    RequestPayerChangeView,
    RequestView,
)
from reimbursements.views.transfer import (
    RequestTransferInitiateView,
    RequestTransferClaimView,
)

urlpatterns = [
    path("new", RequestCreateView.as_view(), name="request-new"),
    path("<int:pk>", RequestView.as_view(), name="request"),
    path("<int:pk>/pdf", RequestPDFBundleView.as_view(), name="request-pdf"),
    path("<int:pk>/beancount", RequestBeancountView.as_view(), name="request-beancount"),
    path("<int:pk>/edit", RequestEditView.as_view(), name="request-edit"),
    path(
        "<int:pk>/submit-draft",
        RequestSubmitDraftView.as_view(),
        name="request-submit-draft",
    ),
    path("<int:pk>/review", RequestReviewView.as_view(), name="request-review"),
    path(
        "<int:pk>/bank-details",
        BankFormSelectorView.as_view(),
        name="bank-form-selector",
    ),
    path(
        "<int:pk>/bank-details/<str:wise_type>",
        BankDetailsView.as_view(),
        name="bank-details",
    ),
    path("<int:pk>/submit", RequestSubmitView.as_view(), name="request-submit"),
    path("<int:pk>/delete", RequestDeleteView.as_view(), name="request-delete"),
    path(
        "<int:pk>/reimburse", RequestReimburseView.as_view(), name="request-reimburse"
    ),
    path(
        "<int:pk>/reimburse-return",
        RequestReimburseReturnView.as_view(),
        name="request-reimburse-return",
    ),
    path(
        "<int:pk>/request-increase",
        RequestSubmitIncreaseView.as_view(),
        name="request-submit-increase",
    ),
    path(
        "<int:pk>/request-comment",
        RequestCommentView.as_view(),
        name="request-comment",
    ),
    path(
        "<int:pk>/change-currency",
        RequestCurrencyChangeView.as_view(),
        name="request-change-currency",
    ),
    path(
        "<int:pk>/change-payer",
        RequestPayerChangeView.as_view(),
        name="request-change-payer",
    ),
    path("<int:pk>/receipts", RequestReceiptsView.as_view(), name="request-receipts"),
    path(
        "<int:request_id>/receipts/new", ReceiptCreateView.as_view(), name="add-receipt"
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/delete",
        ReceiptDeleteView.as_view(),
        name="delete-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/edit",
        ReceiptEditView.as_view(),
        name="edit-receipt",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/thumbnail",
        ReceiptThumbnailView.as_view(),
        name="view-receipt-thumbnail",
    ),
    path(
        "<int:request_id>/receipts/<int:pk>/view-file",
        ReceiptFileView.as_view(),
        name="view-receipt-file",
    ),
    path(
        "<int:pk>/transfer",
        RequestTransferInitiateView.as_view(),
        name="request-transfer-initiate",
    ),
    path(
        "transfer/<str:token>",
        RequestTransferClaimView.as_view(),
        name="request-transfer-claim",
    ),
]

src/webui/urls.py
from django.urls import path

from webui.views import DeleteBankDetailsView, IndexView, ProfileEditView, ProfileView

urlpatterns = [
    path("", IndexView.as_view()),
    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/edit", ProfileEditView.as_view(), name="profile-edit"),
    path(
        "profile/delete-bank-details",
        DeleteBankDetailsView.as_view(),
        name="profile-delete-bank-details",
    ),
]

src/reimbursements/models/receiptline.py
import datetime
from decimal import Decimal
from functools import lru_cache

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

from historical_currencies.exceptions import ExchangeRateUnavailable
from historical_currencies.exchange import exchange

from reimbursements.models.receipt import Receipt
from reimbursements.models.request import Request
from reimbursements.models.types import ExpenseType


@lru_cache
def conversion_leeway_minimum(currency: str, date: datetime.date) -> Decimal:
    """Convert CONVERSION_LEEWAY_MINIMUM_USD to currency for date."""
    usd_minimum = Decimal(settings.CONVERSION_LEEWAY_MINIMUM_USD)
    return exchange(usd_minimum, "USD", currency, date)


class ReceiptLine(models.Model):
    receipt = models.ForeignKey(Receipt, on_delete=models.CASCADE, related_name="lines")
    date = models.DateField()
    description = models.TextField()
    amount = models.DecimalField(decimal_places=2, max_digits=15)
    currency = models.CharField(max_length=3)
    converted_amount = models.DecimalField(decimal_places=2, max_digits=15)
    expense_type = models.ForeignKey(ExpenseType, on_delete=models.PROTECT)

    @property
    def qualified_amount(self):
        return (self.amount, self.currency)

    @property
    def qualified_converted_amount(self):
        return (self.converted_amount, self.receipt.request.currency)

    @property
    def automatically_converted_amount(self):
        return exchange(
            self.amount, self.currency, self.receipt.request.currency, self.date
        )

    @property
    def qualified_automatically_converted_amount(self):
        return (self.automatically_converted_amount, self.receipt.request.currency)

    @property
    def conversion_within_limits(self):
        if not self.receipt.custom_conversion:
            return True
        request_currency = self.receipt.request.currency
        leeway_minimum = conversion_leeway_minimum(request_currency, self.date)
        auto_converted = self.automatically_converted_amount
        difference = self.converted_amount - auto_converted
        if difference < leeway_minimum:
            return True
        ratio = self.converted_amount / auto_converted
        leeway = Decimal(1 + settings.CONVERSION_LEEWAY_PERCENTAGE / 100)
        return ratio <= leeway

    def clean(self):
        super().clean()
        request = None
        currency_to = getattr(self, "initial_request_currency", None)
        try:
            request = self.receipt.request
            currency_to = request.currency
        except Receipt.DoesNotExist:
            pass
        except Request.DoesNotExist:
            pass
        if (
            self.amount
            and self.currency
            and currency_to
            and not self.receipt.custom_conversion
        ):
            try:
                self.converted_amount = exchange(
                    amount=self.amount,
                    currency_from=self.currency,
                    currency_to=currency_to,
                    date=self.date,
                )
            except ExchangeRateUnavailable:
                raise ValidationError(
                    {
                        "currency": _(
                            "No exchange rate available for %(currency_from)s "
                            "to %(currency_to)s for %(date)s. Please contact "
                            "an admin to get it imported."
                        )
                        % {
                            "currency_from": self.currency,
                            "currency_to": currency_to,
                            "date": self.date,
                        }
                    }
                )

        if (
            request
            and self.expense_type_id
            and not self.expense_type.request_types.filter(pk=request.request_type.pk)
        ):
            raise ValidationError(
                {
                    "expense_type": _("%s is not a valid expense type for %s requests")
                    % (self.expense_type.name, request.request_type.name),
                }
            )


@receiver(post_save, sender=Request)
def update_receipt_conversions(sender, instance, **kwargs):
    """Update converted_amounts. Backstop for things like edits in admin."""
    for receipt in instance.receipts.all():
        for line in receipt.lines.all():
            line.clean()
            line.save()

src/reimbursements/forms/lifecycle.py
from django import forms
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper


class RequestSubmitForm(forms.Form):
    compliant = forms.BooleanField(
        label=_(
            "The expenses, for which I seek reimbursement, are compliant with "
            "the policies of the project and the fiscal sponsor."
        )
    )
    sole_source = forms.BooleanField(
        label=_(
            "I have not sought nor will seek reimbursement of these "
            "expenses from any other source."
        )
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_tag = False

src/reimbursements/forms/requestline.py
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from crispy_forms.helper import FormHelper

from reimbursements.models import Request, RequestLine


class RequestLineForm(forms.ModelForm):
    class Meta:
        model = RequestLine
        widgets = {
            "description": forms.TextInput(),
        }
        exclude = ()


class RequestLineFormHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.form_tag = False
        self.template = f"{settings.CRISPY_TEMPLATE_PACK}/table_inline_formset.html"


class RequestLineInlineFormset(forms.models.BaseInlineFormSet):
    def clean(self):
        count = sum(
            1
            for form in self.forms
            if getattr(form, "cleaned_data", None)
            and not form.cleaned_data.get("DELETE", False)
        )
        if count < 1:
            raise ValidationError(_("At least one request line is required."))
        return super().clean()


RequestLineFormset = forms.models.inlineformset_factory(
    Request,
    RequestLine,
    form=RequestLineForm,
    formset=RequestLineInlineFormset,
    exclude=(),
    extra=1,
)

src/reimbursements/views/bank_details.py
from typing import TYPE_CHECKING

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView

from reimbursements.forms.bank_details import select_form
from reimbursements.models import Profile, Request

if TYPE_CHECKING:
    from django.views.generic.edit import _FormT


class BankFormSelectorView(LoginRequiredMixin, DetailView):
    model = Request
    template_name = "reimbursements/bank_form_selector.html"
    context_object_name = "object"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.bank_details:
            wise_type = self.object.bank_details.get("wise_type")
            context["selected"] = select_form(wise_type=wise_type)
        else:
            try:
                bank_details = self.request.user.profile.bank_details
                if wise_type := bank_details.get("wise_type"):
                    context["saved"] = select_form(wise_type=wise_type)
            except Profile.DoesNotExist:
                pass
        if recommended := select_form(currency=self.object.currency):
            context["recommended"] = recommended
        context["defaults"] = [
            select_form(wise_type="swift"),
            select_form(wise_type="wise"),
        ]
        return context


class BankDetailsView(LoginRequiredMixin, UpdateView):
    model = Request
    template_name = "reimbursements/bank_details.html"
    context_object_name = "object"

    def get_form_class(self):
        wise_type = self.kwargs["wise_type"]
        return select_form(wise_type=wise_type)

    def get_initial(self):
        try:
            bank_details = self.request.user.profile.bank_details
        except Profile.DoesNotExist:
            bank_details = None
        if not bank_details:
            bank_details = {
                "recipient_name": self.request.user.get_full_name(),
                "email": self.request.user.email,
            }
        return bank_details

    def get_context_data(self, **kwargs):
        if not self.object.user_access(self.request.user).get("requester", False):
            raise PermissionDenied("Can only edit your own requests")
        context = super().get_context_data(**kwargs)
        return context

    def form_valid(self, form: "_FormT"):
        Profile.objects.update_or_create(
            user=self.request.user, defaults={"bank_details": form.cleaned_data}
        )
        return super().form_valid(form)

    def get_success_url(self):
        return self.object.get_absolute_url()

src/reimbursements/views/generic.py
from django.db import transaction
from django.http import HttpResponseNotAllowed
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from reimbursements.forms.requestline import RequestLineFormset


class FormAndSetMixin:
    """
    A Class Based View mixin for a primary form with dependent formset

    Basically, a fairly minimal thing that combines with CreateView/UpdateView
    """

    def get_formset_class(self):
        """
        Returns the formset class to use in this view
        """
        return self.formset_class

    def get_formset(self, formset_class, instance=None):
        """
        Returns an instance of the formset to be used in this view.
        Optionally takes the takes the instance of the parent object.
        """
        kwargs = self.get_form_kwargs()
        if instance:
            kwargs["instance"] = instance
        return formset_class(**kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "formset" not in context:
            context["formset"] = RequestLineFormset()
        return context

    def get(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        if form.is_valid():
            self.object = form.save(commit=False)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class, instance=self.object)
        if self.is_valid(form, formset):
            return self.forms_valid(form, formset)
        else:
            return self.forms_invalid(form, formset)

    def is_valid(self, form, formset):
        return form.is_valid() and formset.is_valid()

    def form_valid(self, form):
        raise NotImplementedError("Should be calling forms_valid()")

    def form_invalid(self, form):
        raise NotImplementedError("Should be calling forms_invalid()")

    def forms_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(form=form, formset=formset)
        )

    def forms_valid(self, form, formset):
        with transaction.atomic():
            self.object.save()
            formset.save()
        return self.get_success_url()

    def get_success_url(self):
        return redirect(self.object.get_absolute_url())


class FormAndSetCreateView(FormAndSetMixin, CreateView):
    """A form+formset CreateView"""

    def get(self, request, *args, **kwargs):
        self.object = None
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        return super().post(request, *args, **kwargs)


class FormAndSetUpdateView(FormAndSetMixin, UpdateView):
    """A form+formset UpdateView"""

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)


class DetailActionView(DetailView):
    """A DetailView for performing actions only"""

    def get(self, request, *args, **kwargs):
        # DetailView provides a get()
        return HttpResponseNotAllowed(["post"])

src/reimbursements/templates/reimbursements/bank_details.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
{% trans "Add Bank Details" %}
{% endblock %}
{% block content %}
<h1>{% trans "Add Bank Details" %}</h1>
<p>
  {% url "bank-form-selector" object.pk as selector_url %}
  {% blocktrans %}
    Please enter the appropriate details for your bank.
    If this is not the appropriate kind of transfer for your bank, please
    <a href="{{ selector_url }}">select</a> another form.
  {% endblocktrans %}
</p>
<h2>{{ form.description }}</h2>
<form method="post">
  {% crispy form %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}">
</form>
{% endblock %}

src/reimbursements/templates/reimbursements/bank_form_selector.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
{% trans "Select Bank Transfer Type" %}
{% endblock %}
{% block content %}
<h1>{% trans "Select Bank Transfer Type" %}</h1>
<p>{% trans "Please select an appropriate transfer method for your bank." %}</p>
{% if selected %}
  <h2>{% trans "Previously Selected:" %}</h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=selected.wise_type %}"
    >{{ selected.description }}</a>
  </div>
{% endif %}
{% if saved %}
  <h2>{% trans "Previously Saved:" %}</h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=saved.wise_type %}"
    >{{ saved.description }}</a>
  </div>
{% endif %}
{% if recommended %}
  <h2>
    {% blocktrans with currency=object.currency %}
      Recommended for {{currency}}:
    {% endblocktrans %}
  </h2>
  <div>
    <a class="btn btn-primary"
       href="{% url "bank-details" pk=object.pk wise_type=recommended.wise_type %}"
    >{{ recommended.description }}</a>
  </div>
{% endif %}
<h2>{% trans "Default:" %}</h2>
<div>
  {% for option in defaults %}
    <a class="btn btn-success"
       href="{% url "bank-details" pk=object.pk wise_type=option.wise_type %}"
    >{{ option.description }}</a>
  {% endfor %}
</div>
{% endblock %}

src/reimbursements/templates/reimbursements/edit_receipt.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
  {{ view.request_model.subject }}:
  {% if object.pk %}
    {% trans "Edit Receipt" %}
  {% else %}
    {% trans "New Receipt" %}
  {% endif %}
{% endblock %}
{% block content %}
<h1>
  {{ view.request_model.subject }}:
  {% if object.pk %}
    {% trans "Edit Receipt" %}
  {% else %}
    {% trans "New Receipt" %}
  {% endif %}
</h1>
{% if object.pk %}
  <form method="post" action="{% url "delete-receipt" view.request_model.id object.id %}" class="d-inline">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" name="delete"
           value="{% trans "Delete Receipt" %}">
  </form>
  <a class="btn btn-info" href="{% url "view-receipt-file" view.request_model.id object.id %}">View File</a>
{% endif %}
<form method="post" enctype="multipart/form-data" id="edit_form">
  {% crispy form %}
  <h2>{% trans "Receipt Lines" %}</h2>
  <div class="form-text">
    {% blocktrans %}
      Break up the receipt into lines, if necessary.
      Most of the time you only need a single line to capture a receipt, but
      you can use more, if you need to describe different expenses.
    {% endblocktrans %}
  </div>
  <div class="form-text">
    {% blocktrans %}
      Please accurately record the total (or, if necessary, lines) of the receipt.
      If you are not requesting full reimbursement for the invoice, list the
      relevant lines and values only and note that the request is partial, in
      the description.
    {% endblocktrans %}
  </div>
  <div class="form-text">
    {% blocktrans with currency=view.request_model.currency %}
      If you are using custom conversions, you can leave the "Amount converted to
      {{ currency }}" field blank to automatically calculate a mid-market
      conversion for a line.
    {% endblocktrans %}
  </div>
  {# https://github.com/django-crispy-forms/crispy-bootstrap5/issues/174 #}
  {% include "bootstrap5/errors_formset.html" %}
  {% crispy formset formset_helper %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <a class="btn btn-secondary" id="add_line">{% trans "Add Line" %}</a>
  <input type="submit" class="btn btn-primary" value="{% trans 'Save' %}">
</form>
{% endblock %}
{% block extra_foot %}
{{ valid_expense_types|json_script:"valid_expense_types"}}
<script>
  "use strict";
  (function() {
    const converted_amount_visible = ((visible) => {
      const hidden = !visible;
      const th = document.querySelector("form th[for$=-converted_amount]");
      th.hidden = hidden;
      document.querySelectorAll("form td[id$=-converted_amount]").forEach(td => {
        td.hidden = hidden;
      });
    });

    const custom_conversion_field = document.getElementById("id_custom_conversion");
    converted_amount_visible(custom_conversion_field.checked);

    // Empty all converted amounts if custom_conversion is disabled, to force
    // recalculation
    custom_conversion_field.addEventListener("change", (event) => {
      converted_amount_visible(custom_conversion_field.checked);
      if (!custom_conversion_field.checked) {
        const inputs = document.querySelectorAll("form input[id$=-converted_amount]");
        inputs.forEach(input => {input.value = "";});
      }
    });

    const update_total = function(event) {
      var totals = {};
      document.querySelectorAll("form tbody tr:not(.empty-form)").forEach(row => {
        const deleted = row.querySelector("input[id$=-DELETE").checked;
        const currency = row.querySelector("select[id$=-currency]").value;
        const amount = parseFloat(row.querySelector("input[id$=-amount]").value) || 0;
        if (!deleted) {
          totals[currency] = (totals[currency] || 0) + amount;
        }
      });
      var rendered = '';
      for (const currency in totals) {
        if (rendered) {
          rendered += ", ";
        }
        rendered += new Intl.NumberFormat("en-US", {
          style: "currency",
          currency: currency,
        }).format(totals[currency]);
      }
      document.querySelector("span#total").textContent = rendered;
    }

    const update_total_listener_selector = "select[id$=-currency], input[id$=-amount], input[id$=-DELETE]";
    document.querySelectorAll(update_total_listener_selector).forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();

    const add_button = document.querySelector("#add_line");
    add_button.addEventListener("click", (event) => {
      const total_forms_input = document.querySelector("#id_lines-TOTAL_FORMS");
      const index = parseInt(total_forms_input.getAttribute("value"));
      const empty_form = document.querySelector(".empty-form");
      const new_form = empty_form.innerHTML.replace(/__prefix__/g, index);
      empty_form.parentElement.insertAdjacentHTML("beforeend", new_form);
      const new_row = empty_form.parentElement.lastElementChild;
      total_forms_input.setAttribute("value", index + 1);
      new_row.querySelectorAll(update_total_listener_selector).forEach(el => {
        el.addEventListener("input", update_total);
      });
    });

    const valid_expense_types = JSON.parse(
      document.getElementById("valid_expense_types").textContent);
    document.querySelectorAll("select[id$=-expense_type]").forEach(el => {
      el.querySelectorAll("option").forEach(opt => {
        if (opt.value) {
          opt.disabled = !valid_expense_types.includes(parseInt(opt.value));
        }
      });
    });
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/edit_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_title %}
  {% if object.pk %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
{% endblock %}
{% block content %}
<h1>
  {% if object.pk %}
    {% trans "Edit Request" %}
  {% else %}
    {% trans "New Request" %}
  {% endif %}
</h1>
<p>
  {% blocktrans %}
    This is a request for budget pre-approval to make an expense for the
    project.
    You don't need to break it down into every expected item, just into broad
    categories, for review of your request.
    Once approved, you may make the expenses and will get an opportunity to
    upload receipts.
  {% endblocktrans %}
</p>
<form method="post">
  {% crispy form %}
  {# https://github.com/django-crispy-forms/crispy-bootstrap5/issues/174 #}
  {% include "bootstrap5/errors_formset.html" %}
  {% crispy formset formset_helper %}
  <div class="fs-4 pb-3">
    {% trans "Total:" %}
    <span id="total">{% trans "Calculated by Javascript..." %}</span>
  </div>
  <a class="btn btn-secondary" id="add_line">{% trans "Add Item" %}</a>
  <input type="submit" class="btn btn-primary" value="{% trans 'Save Draft' %}">
</form>
{% endblock %}
{% block extra_foot %}
{{ expense_type_map|json_script:"expense_type_map"}}
<script>
  "use strict";
  (function() {
    const update_total = function(event) {
      var total = 0;
      document.querySelectorAll("form tbody tr:not(.empty-form)").forEach(row => {
        const deleted = row.querySelector("input[id$=-DELETE").checked;
        const amount = parseFloat(row.querySelector("input[id$=-amount]").value) || 0;
        if (!deleted) {
          total += amount;
        }
      });
      const currency = document.querySelector("select#id_currency").value;
      const rendered = new Intl.NumberFormat("en-US", {
        style: "currency",
        currency: currency,
      }).format(total);
      document.querySelector("span#total").textContent = rendered;
    }

    document.querySelector("select#id_currency").addEventListener("input", update_total);
    const update_total_listener_selector = "input[id$=-amount], input[id$=-DELETE]";
    document.querySelectorAll(update_total_listener_selector).forEach(el => {
      el.addEventListener("input", update_total);
    });
    update_total();

    const add_button = document.querySelector("#add_line");
    add_button.addEventListener("click", (event) => {
      const total_forms_input = document.querySelector("#id_lines-TOTAL_FORMS");
      const index = parseInt(total_forms_input.getAttribute("value"));
      const empty_form = document.querySelector(".empty-form");
      const new_form = empty_form.innerHTML.replace(/__prefix__/g, index);
      empty_form.parentElement.insertAdjacentHTML("beforeend", new_form);
      const new_row = empty_form.parentElement.lastElementChild;
      total_forms_input.setAttribute("value", index + 1);
      new_row.querySelectorAll(update_total_listener_selector).forEach(el => {
        el.addEventListener("input", update_total);
      });
    });

    const expense_type_map = JSON.parse(
      document.getElementById("expense_type_map").textContent);
    const request_type_select = document.querySelector("select#id_request_type");
    const update_expense_types = function(event) {
      const request_type = parseInt(request_type_select.value);
      const valid_expense_types = expense_type_map[request_type] || [];
      document.querySelectorAll("select[id$=-expense_type]").forEach(el => {
        el.querySelectorAll("option").forEach(opt => {
          if (opt.value) {
            opt.disabled = !valid_expense_types.includes(parseInt(opt.value));
          }
        });
      });
    };
    request_type_select.addEventListener("input", update_expense_types);
    update_expense_types();
  })();
</script>
{% endblock %}

src/reimbursements/templates/reimbursements/submit_request.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load currency_format %}
{% block page_title %}
{% trans "Submit Request" %}
{% endblock %}
{% block content %}
<h1>{% trans "Submit Request" %}</h1>
<div>{% trans "By submitting this reimbursement request, I declare:" %}</div>
<form method="post">
  {% crispy form %}
  <input type="submit" class="btn btn-primary" value="{% trans 'Submit' %}">
</form>
{% endblock %}

src/reimbursements/templates/reimbursements/transfer_initiated.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load currency_format %}
{% block page_title %}
{% trans "Transfer Initiated" %}
{% endblock %}
{% block content %}
<h1>{% trans "Transfer Code" %}</h1>
<p>
  {% blocktrans %}
    To transfer this request, send this link to the new owner:
  {% endblocktrans %}
</p>
<div class="alert alert-info">
  <div class="float-end copy" role="button" data-bs-toggle="popover" data-bs-trigger="focus" title="{% trans "Copied" %}">
    <i class="bi bi-clipboard"></i>
  </div>
  <div class="user-select-all font-monospace">{{ object.transfer.get_fully_qualified_url }}</div>
</div>
<p>
  {% blocktrans with expires=object.transfer.expires|date:"SHORT_DATETIME_FORMAT" %}
    Valid until: {{ expires }}
  {% endblocktrans %}
</p>
{% endblock %}
{% block extra_foot %}
<script>
  "use strict";
  (function() {
    const btn = document.querySelector(".copy");
    const popover = new bootstrap.Popover(btn);
    const token = document.querySelector(".user-select-all");
    btn.addEventListener("click",  (event) => {
      navigator.clipboard.writeText(token.textContent);
      popover.show();
    });
  })();
</script>
{% endblock %}